### ISSUE TITLE
bootstrap.js missing in the yesod-sqlite template

### ISSUE THREAD

**Issue by frt** [commercialhaskell/stack-templates#109]
This template includes only the `bootstrap.css` file, so lines like the following doesn't work. This is from the `default-layout.hamlet` that comes with the template:
    
    <button type="button" .navbar-toggle.collapsed data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">

To solve this in my project I put the following lines in the `default-layout-wrapper.hamlet`, so it gets the bootstrap from a CDN. 

    \
    \
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    \
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    \
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">

Don't know if this is a good solution to the template.

**Comment by snoyberg** [comment]
Can you open this on the yesodweb/yesod-scaffold repo instead? It will be
easier to pull in the right people there.

**Comment by frt** [comment]
Many thanks! Only now I see that the files from the templates are in the branches of yesodweb/yesod-scaffold. There is easyer to contribute to the template with fixes I'm doing in my project.
