### ISSUE TITLE
Servant docker: compiler version mismatch

### ISSUE THREAD

**Issue by andys8** [commercialhaskell/stack-templates#113]
Using the `servant-docker` template leads currently to this:

```sh
Compiler version mismatched, found ghc-8.2.1 (x86_64), but expected minor version match with ghc-8.0.2 (x86_64) (based on resolver setting in /app/user/stack.yaml).
To install the correct GHC into /root/.stack/programs/x86_64-linux/, try running "stack setup" or use the "--install-ghc" flag.
```

The cause is the generated `Dockerfile` is depending on `haskell:8`:
https://github.com/commercialhaskell/stack-templates/blob/master/servant-docker.hsfiles#L158

The currently recent haskell docker file is in version `8.2.1` and uses ghc `8.2.1`:
https://github.com/freebroccolo/docker-haskell/blob/master/8.2/Dockerfile

The template was probably meant to be used with `8.0.x` instead, which is using ghc `8.0.2`
https://github.com/freebroccolo/docker-haskell/blob/master/8.0/Dockerfile

The simple solution is to depend on `haskell:8.0` instead of `haskell:8`.

**Comment by mgsloan** [comment]
Thanks a bunch for the report and fix!

**Comment by andys8** [comment]
Thanks for the immediate reply and merge 👍
