### ISSUE TITLE
Why is cabal file ignored via .gitignore?

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/stack-templates#116]
I'm writing a bunch of newbie-friendly tutorials and noticed the following in `.gitignore`

```
.stack-work/
exercises.cabal
*~
```

PS: This is the result of `stack init --bare --resolver=9.14 exercises`

Any reason why the cabal file is being explicitly ignored? Has this already been discussed before?

**Comment by snoyberg** [comment]
It's because it's a generated file, coming from package.yaml. It's
generally good practice to not include generated files in Git repos.

**Comment by saurabhnanda** [comment]
Thanks, I realized that `hpack` is being used after posting this issue.
