### ISSUE TITLE
hpack support

### ISSUE THREAD

**Issue by flip111** [commercialhaskell/stack-templates#119]
Wouldn't it be a good idea to convert templates from cabal to hpack? Or perhaps the templates could provide both so users can choose?

**Comment by mgsloan** [comment]
Yes, but it requires work!  And providing both options would make modifications more difficult.  TBH I'm not sure if maintaining templates is really worth their value - https://github.com/commercialhaskell/stack-templates/issues/56 - https://github.com/commercialhaskell/stack-templates/issues/55.  I can think of some very fancy solutions to this, namely having one very simple template and expressing the others as combinations of automated refactorings atop it.

**Comment by flip111** [comment]
Maybe you want to close this in favor of those other issues. Perhaps add this to a list of bullet points what you want to accomplish.

**Comment by mgsloan** [comment]
Sounds good!  Yeah, not sure what to do about it.  One option might be to have some way of representing templates as hackage packages.  That way there'd be a central place for people to upload them.  Currently the maintainer burden is centralized.
