### ISSUE TITLE
Yesod templates should have InstanceSigs

### ISSUE THREAD

**Issue by parsonsmatt** [commercialhaskell/stack-templates#122]
Types are the best documentation, and I'm looking up the method signatures on these functions a lot when I'm getting back into Yesod development.

Including `InstanceSigs` and type signatures on the methods would make this much easier :smile:

**Comment by snoyberg** [comment]
This should be opened against https://github.com/yesodweb/yesod-scaffold/.

**Comment by parsonsmatt** [comment]
Neat, I'll make an issue/raise a PR there :smile: Thanks!
