### ISSUE TITLE
Error building servant-docker template project using docker-compose

### ISSUE THREAD

**Issue by matteougolotti** [commercialhaskell/stack-templates#126]
The servant-docker template seems to be broken, as it fails to build using docker-compose.

Steps to reproduce:

stack new test-project servant-docker
cd test-project
docker-compose up

The build error I'm getting:

Step 5/8 : RUN export PATH=$(stack path --local-bin):$PATH
 ---> Running in 81444355df0d
Downloading lts-11.11 build plan ...
Downloaded lts-11.11 build plan.
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""

**Comment by parsonsmatt** [comment]
That stack bug was fixed in >1.6 I believe. So we'd need to upgrade the `stack` version in the docker container.

**Comment by matteougolotti** [comment]
Changing the docker image from 8.0 to 8.2.2 seems to fix the issue.
