### ISSUE TITLE
How do I add new templates locally?

### ISSUE THREAD

**Issue by CRogers** [commercialhaskell/stack-templates#13]
The [stack guide says to look at this repo to add more templates](https://github.com/commercialhaskell/stack/blob/master/doc/GUIDE.md#templates). But the `stack-templates` readme doesn't explain how to add templates locally. How do you?

**Comment by narrative** [comment]
Hi,

Currently there is no support for local templates. However, (it is planned for the future)[https://github.com/commercialhaskell/stack/issues/783]

For the time being, making pull requests to this repository is how new templates have been being added.

**Comment by tfausak** [comment]
commercialhaskell/stack#1095 landed a few days ago.

**Comment by cies** [comment]
So this can be closed :)
