### ISSUE TITLE
ghcjs template does not produce any JavaScript file

### ISSUE THREAD

**Issue by mnn** [commercialhaskell/stack-templates#131]
Steps I took:
```
$ stack new ghcjs
$ cd ghcjs
$ stack build
```
Running `find . -type f -iname '*.js'` doesn't return any result. I am doing something wrong? I thought templates were supposed to be a complete setup of a project.

Stack version: Version 1.6.3, Git revision b27e629b8c4ce369e3b8273f04db193b060000db (5454 commits) x86_64 hpack-0.20.0

**Comment by mihaimaruseac** [comment]
Probably because these got obsoleted they were not updated.

**Comment by mnn** [comment]
Oh, thank you for a quick reply. After failing to install ghcjs by hand I tried the template. What is the reason of not updating it? I hope ghcjs is not dead, I would love to try Haskell in browser.

**Comment by mihaimaruseac** [comment]
There is no one working on ghcjs and Stack at the same time to update this.

See https://github.com/commercialhaskell/stack/issues/4086

**Comment by mnn** [comment]
Thanks again. I will take a look at the mentioned Nix, maybe I'll have better luck with that.
