### ISSUE TITLE
Wiki would benefit from update for stack 1.9

### ISSUE THREAD

**Issue by dbaynard** [commercialhaskell/stack-templates#132]
In stack 1.9, template handling has changed to introduce namespaces (though this repo remains the default for non-namespaced templates).

Note: there's currently an issue commercialhaskell/stack#4394 which means github repos must be prefixed with `github:` on Windows.

**Comment by dbaynard** [comment]
I've added some details — but it is still fairly sparse.

**Comment by mpilgrem** [comment]
I have done another pass of the Wiki (for the position in 2022) and will close this issue.
