### ISSUE TITLE
keep-a-changelog

### ISSUE THREAD

**Issue by Bergmaier** [commercialhaskell/stack-templates#135]
Hi,
I found https://keepachangelog.com/ really helpful and would like to see it linked from the empty changelog template. Opinions?

**Comment by mihaimaruseac** [comment]
Sounds good. Can you make a PR, please?

**Comment by Bergmaier** [comment]
Which file to edit? I've found a changelog in four of them. The one for `haskeleton` is the most complete. I believe I've only used `new-template` till now. Should the CHANGELOG.md part be the same everywhere or is there a difference?

**Comment by mihaimaruseac** [comment]
Oh, these are the templates. I don't it's worth changing here as stack will move away from a single-point-of-truth for these

**Comment by Bergmaier** [comment]
Where else to change? Won't `stack` keep this as a default in some way?
