### ISSUE TITLE
tasty-travis template is broken

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack-templates#140]
```
≻ stack new doctest-bug tasty-travis
Downloading template "tasty-travis" to create project "doctest-bug" in doctest-bug/ ...
The template "tasty-travis" is invalid and could not be used. The error was: InvalidInput "{-# START_FILE {{ name }}.cabal #-}"
```

I was looking for a template including doctests

`readme-lhs` seems to have them too, but the literate Haskell syntax is very confusing! ;)

**Comment by haskellGardener** [comment]
Change first line to: {-# START_FILE {{name}}.cabal #-}
fussy impermissible whitespace

**Comment by mihaimaruseac** [comment]
Sorry, I forgot to push branch back in July. This is fixed now

**Comment by sjakobi** [comment]
Thank you @mihaimaruseac! :)
