### ISSUE TITLE
Mention Stack-Templatizer?

### ISSUE THREAD

**Issue by prikhi** [commercialhaskell/stack-templates#142]
Heya, I wrote a small application the other day for turning a folder into a stack template:
https://github.com/prikhi/stack-templatizer

Essentially you create the folders and files for a template, run the application, and it'll build the `hsfiles` template for you. So you can use your editor's linting, autoformatting, etc when building out the template.

I'm wondering if you'd like to stick a link to the app in your readme or something?

**Comment by mpilgrem** [comment]
I added something to `README.md` under 'related initatives'.
