### ISSUE TITLE
Desired WASM template for documenting sensible defaults

### ISSUE THREAD

**Issue by robwithhair** [commercialhaskell/stack-templates#156]
Hi there,

I don't know much about compiling Haskell for WASM, which I understand is still quite new.  I don't know what the recommended approach is at this time for front-end web, but I think it would be helpful if there was a starting point in the stack templates.  

Would anyone be interested in providing advise to help me put a template for wasm together? 

I know there is now a WebAssembly backend merged into GHC, but I don't know how practical it is ATM?  I also know there are several other projects providing compilers ATM, but are they any good?  Does anyone have any practical experience in their usage they could share?  

Can anyone with knowledge and experience of using any of the above help advise me of which tooling as a starting point, or is it not ready / possible at this time?  

Thanks,

Rob

**Comment by mpilgrem** [comment]
@robwithhair, if you also post your request at the [Haskell Community](https://discourse.haskell.org/), I think more relevant people will be aware of it.

**Comment by robwithhair** [comment]
Thanks, that's ideal.  I have posted as advised.

**Comment by mpilgrem** [comment]
Closing, noting that @robwithhair's request for help can be found here: https://discourse.haskell.org/t/desired-wasm-template-for-documenting-sensible-defaults/6358.
