### ISSUE TITLE
Strange message when using `stack new`

### ISSUE THREAD

**Issue by NorfairKing** [commercialhaskell/stack-templates#158]
When you generate a Haskell project with stack, you get this message when executing tests:

> Test suite not yet implemented

This seems to imply that Haskellers write tests.
I would prefer if it said "No test suite implemented."

**Comment by mpilgrem** [comment]
@NorfairKing, if your underlying request is for a template that is like the default `new-template` but without the framework for a test suite, I would be willing to add it here. The default is, I think, indeed, based on the view that test suites are a Good Thing and, so, the barriers to them being included in packages should be lowered.
