### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by tiredpixel** [commercialhaskell/stack-templates#23]
Hello. Would it be possible to confirm the licence for these templates, please, for those parts which are not explicitly annotated already? For instance, `yesod-postgres.hsfiles` bundles Bootstrap as `static/css/bootstrap.css` which is licensed under MIT, but for the main parts of the templates themselves, I can't find a licence annotation, nor is there anything about it in `README.md`, nor is there a `LICENSE*` file. Thanks! Peace, tiredpixel

**Comment by snoyberg** [comment]
I've added a LICENSE file.

**Comment by tiredpixel** [comment]
@snoyberg, thank you, much obliged! :)
