### ISSUE TITLE
A feature for displaying message before completing successfully

### ISSUE THREAD

**Issue by cies** [commercialhaskell/stack-templates#24]
With the `yesod init` command it displayed a beginner friendly message after completing successfully. This functionality is lost now.

I want to suggest how to implement this in `stack new`. If you like this approach I hope to find time to implement it.

What about having a `{-# START_SUCCESS_MESSAGE #-}` to signify where the message starts. It think can be a mustache template like anything else. Good approach?

**Comment by snoyberg** [comment]
Since this is a feature that needs to be implemented in Stack itself, can
you reopen against the Stack repo?

**Comment by mgsloan** [comment]
Seems relevant to https://github.com/commercialhaskell/stack/issues/1571 , perhaps add a comment there?  I agree that this would be cool.  Maybe it'd be enough to display the description after initialization?
