### ISSUE TITLE
ghcjs template will need update for improved-base

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack-templates#25]
Or maybe a whole new template? I can provide that if it sounds good. The only (current) change is that the IsString instance of JSString moved locations, so Lib.hs needs

    - import GHCJS.Foreign ()
    + import Data.JSString ()

**Comment by mgsloan** [comment]
My reasoning for having it target the old-base version is that for it we actually have a reasonably static snapshot :) .   Whereas improved-base is still a moving target.

I agree, though, it would be nice to have a template for improved-base, and probably makes sense to have it be the canonical ghcjs template.  How about renaming the current one to `ghcjs-old-base`, and having this fixed one for `ghcjs`.
