### ISSUE TITLE
yesod-sqlite template only supports persiting data, but not retriving it?

### ISSUE THREAD

**Issue by Wizek** [commercialhaskell/stack-templates#27]
I've tried out the yesod-sqlite example, and thought it was broken because no mater what I did on the page, upon refresh all my entered data were gone, e.g. comments.

So I started looking into the code, and it seems to me that the yesod-sqlite template was written only to persist data into the database, but never to retrieve it?

https://github.com/commercialhaskell/stack-templates/blob/master/yesod-sqlite.hsfiles#L1064

I am not sure if my quick assessment is correct, could also be some other issue. Is this template supposed to showcase only persisting data without ever retrieving it?

**edit**: I've checked the database and it does contain the correctly set up schema and some of my comments, but when I navigate to http://localhost:3000 I don't see anything I've entered.

**edit 2**: I've also ran `stack test`. Even though the tests are green, reading them I don't see any tests checking if any page served up contains anything persisted.

**edit 3** @ 2016-01-18T18:00:14: Okay, managed to make it work! 

https://github.com/Wizek/yesod-sqlite/commit/1c3cae31edad408567d8e12d13987410e61629a9

It might make sense to incorporate something like this into the template, might it not? I'm just beginning to learn Yesod, and it would have saved me a few hours trying to figure out. Having a working example always helps me quite a bit. I imagine it could help others too.

**Comment by snoyberg** [comment]
Pinging @gregwebs. Do you know who wrote that part of the scaffolding? I'm not sure what's going on there.

**Comment by gregwebs** [comment]
I have no idea. Why would that part of the scaffolding be any different for sqlite?

**Comment by Wizek** [comment]
I've looked briefly at the MySQL scaffold too, and to me they do indeed seem to be the same in this regard, that they don't showcase reading from the database, only writing to it.

**Comment by mpilgrem** [comment]
I am going to close this issue because (a) the passage of time since the last contribution to the discussion and (b) in the interim, it has been explained (in README.md) that matters related to Yesod templates should target a different repository.
