### ISSUE TITLE
Template should use correct copyright year

### ISSUE THREAD

**Issue by Toxaris** [commercialhaskell/stack-templates#28]
Some templates put "copyright 2015" snippets in `LICENSE` or `*.cabal` files.

Minimal fix: Should be changed to "2016".
Better fix: Should be computed based on system date at call time of `stack new`.

**Comment by narrative** [comment]
Thanks! Just created #29.

Having the date be calculated by ```stack new``` would be a nice feature that should be trivial to add. Recommend creating the issue in the [stack](https://github.com/commercialhaskell/stack) repository.

**Comment by mgsloan** [comment]
Good point!  I've merged that PR, so now templates can use `{{year}}`

**Comment by narrative** [comment]
> Note that we should test what happens when {{something-not-defined}} is used with templates. It wouldn't be good to break old stack versions.

Mustache behaves as follows when a tag is undefined:

| template | output|
---|---
| `{{undefined}}` | |
| `{{undefined}}{{^undefined}}default value{{/undefined}}`|default value|

**Comment by mgsloan** [comment]
I didn't realize that, nice feature!
