### ISSUE TITLE
yesod persistent-odbc mysql

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/stack-templates#35]
Requested by @felipexpert (https://github.com/fpco/stackage/issues/1230). 

> For those who need to run a yesod webapplication on a windows with MySQL, it would be a great help if you guys included among the templates a yesod-mysql-odbc, please.

**Comment by mpilgrem** [comment]
I am going to close this issue because, in the interim: (a) it has been explained (in README.md) that requests for Yesod templates should target a different repository and (b) this repository has announced that it is not accepting new templates
