### ISSUE TITLE
yesod-simple I18N

### ISSUE THREAD

**Issue by felipexpert** [commercialhaskell/stack-templates#42]
I can't find the internationalization stuff in yesod-simple, why??? I have manage to configure it with persistent-odbc, but messages directory isn't present. Do I need to setup the I18N stuff myself?
Side note: Yesod is really awesome!

**Comment by snoyberg** [comment]
The i18n stuff is no longer included in the scaffold, you'll need to set it
up yourself.

Glad you're liking Yesod :)
