### ISSUE TITLE
Opinionated set of warnings by default?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack-templates#47]
I think a good default set of warnings is `-Wall -fwarn-tabs -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates -fwarn-identitites`.  Is this too scary to put in a default cabal file?  I think it'd be good to call attention to these extra safety warnings, which can be disabled if necessary.

It does, however, mean that the ghc-options field can now get quite large.  For example, the test-suite of the default template will have `-threaded -rtsopts -with-rtsopts=-N -Wall -fwarn-tabs -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates -fwarn-identitites`

**Comment by bitemyapp** [comment]
I'm for it :)

**Comment by 3noch** [comment]
Considering we like to sell Haskell for its safety, sometimes I'm baffled at what things managed to end up as warnings and not errors. :scream:
