### ISSUE TITLE
Determine guidelines for template inclusion

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack-templates#55]
How do we determine whether a template should be included in this repo?

I don't really want to end up with a huge pile of templates to maintain, where there's an incentive for library authors to add templates in order to make their package more discoverable.  In other words, ideally the boilerplate code should be stuff that people will want to modify, rather than just delete.  A template should consist of boilerplate which is useful for many projects.

At once, I can see the value of initializing a cabal file with a bunch of dependencies that are commonly used together.

**Comment by narrative** [comment]
Of all the times I've created a new haskell project using stack, I don't think I've ever wanted to reach for a template other than `simple` or `new-template`, even in the cases where I planned on using a library that a template existed for. I'd rather work from a blank slate and add exactly what I need than initialize a template project that has a lot of cruft I'm going to delete immediately. I suspect I'm not alone in this.

I share your concern that as time goes on this repository is growing into a massive pile of mostly-unused templates that are more trouble and time to maintain than it's worth.

Granted, it can be a nice way to get up and running with a library quickly, but as you mention there needs to be somewhere to draw the line.

To be honest, I wouldn't mind seeing this repository shrink or even go away in favor of something similar to rust's `cargo new` which has two templates to choose from: library or binary application.

**Comment by bitemyapp** [comment]
@narrative I'm in favor of what narrative is saying, but I'd be happier if it came with the inclusion of the ability to point at a sub-path in an arbitrary git repo so that people don't have to make other git repos for a template that's relevant to a particular project. Ideally projects like yesod et al. could just have a sub-directory named `stack-templates/` and users could point at one located therein when starting a new project.

**Comment by mgsloan** [comment]
Yeah, I also rarely use anything but the simple template.

It'd be nice to be able to collect stats so that we know what, but that's even more complexity!  Such a feedback mechanism could be quite useful in general, though.

I think the real power tool we want is something that can systemically refactor cabal / stack / hs files.  Then you could init a project with a barebones template, and say something like `stack instantiate hspec` to get an hspec test-suite.  This would be much better than anticipating the needs of the project upfront and picking a template.

**Comment by soenkehahn** [comment]
Reading this discussion, by now, I'm convinced that only having a few very simple, bare templates has huge benefits. I was working on #52, but now I'm not even sure, I still want it as a template.

(Somewhat off-topic:) But what I would love to see is this: a place for example projects with a very lax inclusion policy. Where people can actually add examples for how to combine several libraries. E.g. how to combine `servant` and `heist`; or `scotty` and `persistent`; etc.. This could just be a collection of links to github repos, of course. I thought about having something like this inside the `haskell-servant` github organization, but I don't want this to be `servant`-specific. Does something like this exist already?

**Comment by lethjakman** [comment]
So, ignore me if this is crazy talk, but what about allowing libraries to include their own stack templates? That way the library maintainer is the maintainer of the templates as well. You could perhaps search for a stackTemplates/ directory inside of each project that is already installed and run it from there. It does add some overhead for searching, but it could be cached whenever a project is installed. I don't know if there's any infrastructure in place for this, though.

**Comment by mgsloan** [comment]
@lethjakman That's a cool idea!  I'd like to have a general mechanism for projects to provide development-tool oriented files.  A few examples:

* Package specific hspec rules
* Specification of refactorings needed in order to update to a new library version
* This example, templates included with packages

**Comment by mgsloan** [comment]
Returning to this idea, I really like @lethjakman 's idea.  We could even allow hackage packages that existed entirely for the sake of providing templates.

I am returning to this topic due to the idea of having stack templates for standalone scripts - https://github.com/commercialhaskell/stack/issues/2677

**Comment by mgsloan** [comment]
@lethjakman I have fleshed out a concrete proposal based on your idea: https://github.com/commercialhaskell/stack/issues/2681

**Comment by flip111** [comment]
It would be nice if the templates were scriptable. Then one could start out with a base template, then apply template modifications advised by packages and as last step apply user defined modifications. I also like this to apply not just with `stack new` but also when stack detects that you have included a new package in your cabal/hpack file. As for scripting language / build tool .. i have no idea what would work here.

**Comment by mpilgrem** [comment]
I am going to close this issue given (a) the passage of time since the last contribution to the discussion and (b) in the interim,  the repository has announced that it is not accepting new templates.
