### ISSUE TITLE
Document opinionated decisions which should be consistent across templates

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack-templates#56]
It would be nice if templates were generally consistent with eachother.  For example, https://github.com/commercialhaskell/stack-templates/issues/47

From [here](https://github.com/commercialhaskell/stack-templates/pull/52#issuecomment-204639039):

> Is there some sort of style guide for the final app? For instance, when specifying the executable, should Main.hs live in app/ or bin/ or exe/ or something else?

Maybe it's user discretion / template author discretion.  I like `app/` well.  `src/main/` is nice too, because then all your src is in the same subdir.  Stack uses that, but I'm not sure why.

**Comment by chrisdone** [comment]
Stack uses that because I made the initial commit so I got to decide. :-P Being able to grep src is why.

**Comment by bhipple** [comment]
Is it possible to have templates include other templates to avoid duplication of things like `.gitignore` files?

**Comment by mpilgrem** [comment]
I am going to close this issue given (a) the passage of time since the last contribution to the discussion and (b) in the interim, the repository has announced that it is not accepting new templates.
