### ISSUE TITLE
New license selection parameter in ./stack/config.yaml

### ISSUE THREAD

**Issue by malteneuss** [commercialhaskell/stack-templates#57]
By default the BSD3 license is mentioned in the generated `.cabal` file and downloaded automatically.
Would it be possible to add a new parameter to the stack.yaml in order to specify and download another license like `MIT` or `GPLv3`?

**Comment by mgsloan** [comment]
Yeah, I agree that something like this would be nice.  I mention the same idea here https://github.com/commercialhaskell/stack/issues/1994

**Comment by mgsloan** [comment]
Since it's really a stack feature, I'm going to prefer that issue
