### ISSUE TITLE
yesod-minimal template doesn't support running with `stack exec -- yesod devel`

### ISSUE THREAD

**Issue by silky** [commercialhaskell/stack-templates#60]
it's a bit *too* minimal

probs should at least let it do this.

**Comment by snoyberg** [comment]
This is documented on the [Yesod quickstart page](http://www.yesodweb.com/page/quickstart):

> Also, if you choose the "mini" scaffolding, yesod devel will not work.

**Comment by silky** [comment]
i suppose so; but maybe it could have a very simple devel entrypoint? or do you consider that outside the scope?

**Comment by snoyberg** [comment]
It's outside the scope, it will make the template more complicated than
desired.

On Tue, Apr 19, 2016 at 1:03 PM, Noon van der Silk <notifications@github.com

**Comment by silky** [comment]
okay
