### ISSUE TITLE
Some yesod templates tests fail at first because there's no CSRF middleware

### ISSUE THREAD

**Issue by yamadapc** [commercialhaskell/stack-templates#71]
The `Handler.Comment` specs fail, because of:

https://github.com/commercialhaskell/stack-templates/blob/master/yesod-postgres.hsfiles#L289

Not having:

```
-    yesodMiddleware = defaultYesodMiddleware
+    yesodMiddleware = defaultYesodMiddleware . defaultCsrfMiddleware
```

That change is made by this patch:
https://gist.github.com/4821e3ab96615ec4adda6e431ea93411

The other solution is to remove calls to `addTokenFromCookie` in tests, which seems to be what other yesod templates do.

That change is made by this patch:
https://gist.github.com/4d6a4f7d7ed74a3116d953dec340b359

**Comment by bitemyapp** [comment]
This is great! Would you be able to PR the fixes?

**Comment by yamadapc** [comment]
Sure; I'm opening a PR with the second option, since it doesn't make the boilerplate comments confusing.

**Comment by snoyberg** [comment]
For changes to the Yesod scaffolding, can you submit them instead to https://github.com/yesodweb/yesod-scaffold?

**Comment by yamadapc** [comment]
Should have been closed by https://github.com/commercialhaskell/stack-templates/commit/db41e649c26a141983aa9f9eb9e5144cadf0d057
