### ISSUE TITLE
Unable to launch Docker container for servant-docker Template out of the box

### ISSUE THREAD

**Issue by ramonkeypr** [commercialhaskell/stack-templates#73]
Hello,

It appears that the servant-docker template contains a template for a docker-compose.yml but no actual Dockerfile defining our API's container to use as the image for the api resource in docker-compose.yml.

Is there a common Dockerfile example we can use to build containers on top of the stack toolchain?

Thanks for any feedback.

**Comment by kvanberendonck** [comment]
Same.

**Comment by mgsloan** [comment]
Perhaps the template should be removed?  Better yet, fixed!  Pinging @alexanderkjeldaas

**Comment by kvanberendonck** [comment]
It may be a little simple for most use cases - would love a docker/servant/nginx docker-compose template

**Comment by narrative** [comment]
Should be good to go now. Let me know if you experience any issues with it.
