### ISSUE TITLE
strange(?) base constraints on yesod-*

### ISSUE THREAD

**Issue by CarstenKoenig** [commercialhaskell/stack-templates#83]
I just tried to start a yesod-postgres project with stack (wanted lts-7.10) but the resolver could not choose lts-7.10:

```
* Rejected lts-7.10
    ghc-8.0.1 cannot be used for these packages:
        - YesodTest
    base version 4.9.0.0 found
        - YesodTest requires >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
    Using package flags:
        - YesodTest: dev = False, library-only = False
```

turns out there is this base-constraint in the scaffolded *.cabal* but of course the base-version on [lts-7.10 is `base-4.9.0.0`](https://www.stackage.org/lts-7.10)

**Comment by snoyberg** [comment]
This is intentional, to avoid pulling in GHC 8.0.1, which has a bug the prevents the scaffolded site from compiling. See:

* https://github.com/yesodweb/yesod-scaffold/blob/05c7e991ed3921c46dadb4a790116b487fab013e/PROJECTNAME.cabal#L52
* https://ghc.haskell.org/trac/ghc/ticket/12130

**Comment by CarstenKoenig** [comment]
oh gosh - thank you - I actually tried to upgrade another project ot GHC 8.0.1 before and ran into this bug and just wanted to try a current scaffold to see if it's happening there also

sorry to bother you

**Comment by snoyberg** [comment]
No problem 👍
