### ISSUE TITLE
Timeframe for supporting GHC 8.x in Yesod

### ISSUE THREAD

**Issue by rcook** [commercialhaskell/stack-templates#85]
GHC 8.x support for the Yesod templates has been disabled since this change

https://github.com/commercialhaskell/stack-templates/commit/f8879603d675dcf67e0a3ea3332957b2ed039668

When are we likely to be able to use GHC 8.x with Yesod?

**Comment by bitemyapp** [comment]
The timeline is probably whenever GHC 8.0.2, which fixes the problem, is released.

**Comment by rcook** [comment]
Thanks for the info.
