### ISSUE TITLE
yesod-mysql template has broken "Log in with.." links

### ISSUE THREAD

**Issue by parsonsmatt** [commercialhaskell/stack-templates#87]
Clicking "Log in with Google" gives the following screen:

![image](https://cloud.githubusercontent.com/assets/7310112/21156744/f7ea767c-c144-11e6-8c41-9769cf39ce64.png)

Entire error:
<details>
StatusCodeException (Status {statusCode = 404, statusMessage = "Not Found"}) [("Content-Type","text/html; charset=utf-8"),("Cache-Control","no-cache, no-store, max-age=0, must-revalidate"),("Pragma","no-cache"),("Expires","Mon, 01 Jan 1990 00:00:00 GMT"),("Date","Tue, 13 Dec 2016 19:59:42 GMT"),("Content-Encoding","gzip"),("Server","ESF"),("X-XSS-Protection","1; mode=block"),("Alt-Svc","quic=\":443\"; ma=2592000; v=\"35,34\""),("Transfer-Encoding","chunked"),("X-Response-Body-Start","<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\"><title>Error 404 (Not Found)!!1</title><style>*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id=\"af-error-container\"><a href=//www.google.com/><span id=logo aria-label=Google></span></a><p><b>404.</b> <ins>That\226\128\153s an error.</ins><p>The requested URL was not found on this server. <ins>That\226\128\153s all we know.</ins></div>"),("X-Request-URL","GET https://www.google.com:443/accounts/o8/id")] (CJ {expose = []})
</details>

Log in with yahoo works.

**Comment by snoyberg** [comment]
What resolver and version of yesod-auth is your project using?

**Comment by parsonsmatt** [comment]
Using LTS-6.25, so [this version of yesod-auth](https://www.stackage.org/lts-6.25/package/yesod-auth-1.4.13.5)

**Comment by parsonsmatt** [comment]
Ah, I see that [this has already been taken care of](https://github.com/yesodweb/yesod/pull/1309).

**Comment by snoyberg** [comment]
Can you tell me if upgrading resolves the issue? I can make sure that the next lts-6 gets the latest yesod-auth.

**Comment by parsonsmatt** [comment]
6.26 is exhibiting the same problem. Looks like [1.4.13.5](https://www.stackage.org/lts-6.26/package/yesod-auth-1.4.13.5) in on stackage lts6.26, while 1.4.14 has the fix.

**Comment by snoyberg** [comment]
Right, I meant adding an extra-dep for the appropriate version of yesod-auth

**Comment by parsonsmatt** [comment]
i-am-not-a-smart-man.jpeg 

Adding the extra-dep for `yesod-auth-1.4.14` does not fix the issue. Adding `yesod-auth-1.4.15` doesn't seem to fix either.

**Comment by parsonsmatt** [comment]
Nope, I was doing something *else* wrong. Adding `yesod-auth-1.4.14` as an extra dep does fix the issue.

**Comment by snoyberg** [comment]
Cool, thanks for confirming. I'm working on a new LTS-6 release now. Any reason to keep this issue open?

**Comment by parsonsmatt** [comment]
Not that I can see. Thanks!
