### ISSUE TITLE
Are you taking pull requests on Yesod templates?

### ISSUE THREAD

**Issue by jasonzoladz** [commercialhaskell/stack-templates#9]
I'd like to submit a yesod template that includes:

- yesod-auth-account (user/password setup with email verification and password reset)
- mime-mail-ses

My current setup is for mongoDB, but I could also cover postgres.

In general, however, I wish there was a QQ solution in Yesod for this kind of setup.  Plug-n-play...

**Comment by snoyberg** [comment]
Yes, pull requests are definitely welcome.

**Comment by jasonzoladz** [comment]
Great.  Thanks.
