### ISSUE TITLE
Hand out commit bits for stack-templates

### ISSUE THREAD

**Issue by lwm** [commercialhaskell/stack-templates#93]
Hmmm ... quite a few rotting PRs and issues. Can we open this repository up to more contributors having commit access? Stack templates are cool and shouldn't sit here gathering dust. There's been 34 contributors so far, surely we can manage this :)

Pinging @narrative, @snoyberg and @chrisdone as you are the top 3 commiters.

**Comment by bitemyapp** [comment]
I think this is getting phased out eventually so I'm not sure that makes sense.

**Comment by lwm** [comment]
Oh, that's a shame? Any reason why? 

If it's the maintenance burden then it could be community managed.

**Comment by sbditto85** [comment]
I would be willing to help in any way that I can ... I use the stack templates regularly.

**Comment by snoyberg** [comment]
I'm out of the loop on this. @mgsloan is there some plan to deprecate this repo?

**Comment by bitemyapp** [comment]
@snoyberg IIRC, the notion was to make users able to write their own templates or specify templates not in this repository at some point.

**Comment by mgsloan** [comment]
Yeah, this repo is in a bit of a limbo state.  To me it doesn't seem ideal to encourage folks that write a new library to create a template demonstrating its use.

I think the most relevant stack issue is https://github.com/commercialhaskell/stack/issues/2681

**Comment by lwm** [comment]
Features like commercialhaskell/stack#2681 tend to rot because no one has time and the project is lacking contributors. I'd ask that you give commit access on this repository *now* to people who are contributing and let's see who gets time to drive commercialhaskell/stack#2681 forward. Then you can deprecate this project?

**Comment by mgsloan** [comment]
Sure, something like that makes sense to me

**Comment by lwm** [comment]
Right, add me and @sbditto85? Can close this one off then.

**Comment by snoyberg** [comment]
I've sent both of you invites to the stack-templates team.

**Comment by lwm** [comment]
Thanks @snoyberg!
